version: '3.8'

services:

  fvwebserver:
    build:
      context: ./docker/apache2
    container_name: "fvwebserver"
    restart: "always"
    ports:
      - "8888:80"
      - "4444:443"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_SERVER_NAME=fvdatabase
    links:
      - fvdatabase
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./misc/apache2:/var/log/apache2
      - ./website/backend/api:/var/www/html/api/
    depends_on:
      - fvdatabase
    networks:
      - flatvote

  fvdatabase:
    image: mariadb:latest
    container_name: fvdatabase
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./misc/data_schema.sql:/docker-entrypoint-initdb.d/data.sql
      - ./misc/mysql_data:/var/lib/mysql
    networks:
      - flatvote

  cms:
    image: node:18-buster
    container_name: cms
    user: node
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    # restart: always
    ports:
      - 3000:3000
    networks:
      - flatvote
    volumes:
      - ./website/cms/:/app/cms/
    command: sh -c "cd /app/cms && echo 'wtf' && cat package.json && npm install && npm run start && sleep infinity"
    depends_on:
      - fvdatabase


networks:
  flatvote:
    name: flatvote
