version: '3.8'

services:

  nginx:
    build:
      context: ./backend/docker/nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./backend/public/:/var/www/html/api
    depends_on:
      - php-fpm
      - database
    ports:
      - 8888:80
    networks:
      - flatvote

  php-fpm:
    build:
      context: ./backend/docker/php-fpm
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ./backend/public/:/var/www/html/api
    depends_on:
      - database
    networks:
      - flatvote

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - TZ=America/Mexico_City
    ports:
      - 8081:80
    depends_on:
      - database
    networks:
      - flatvote

  database:
    image: mariadb:latest
    container_name: database
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./backend/data_schema.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - flatvote

  frontend:
    image: node:18-buster
    container_name: frontend
    user: node
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    # restart: always
    ports:
      - 3000:3000
    networks:
      - flatvote
      # preproduction:
      #   aliases:
      #     - frontend
    volumes:
      - ./frontend/:/app/frontend/
    command: sh -c "cd /app/frontend && echo 'wtf' && cat package.json && npm install && npm run start && sleep infinity"
    depends_on:
      - database


networks:
  flatvote:
    name: flatvote
